FROM archlinux:base-devel as builder

RUN pacman -Syu --noconfirm

RUN pacman -S arch-install-scripts --noconfirm

RUN echo 'root:0:1000' > /etc/subuid && \
    echo 'root:0:1000' > /etc/subgid

RUN pacstrap -cKP /mnt  base wget cowsay

FROM scratch

COPY --from=builder /mnt /

RUN cowsay
