#!/usr/bin/ash

build() {
    add_binary /usr/bin/losetup
    add_binary /usr/bin/mount
    add_binary /usr/bin/umount
    add_binary /usr/bin/mkdir
    add_binary /usr/bin/modprobe

    add_module overlay
    add_module squashfs
    add_module loop

    add_runscript
}
