#!/usr/bin/ash

mount_handler_overlay_rootfs() {
    echo "Mount handler for overlay rootfs"
    echo $*

    mount /dev/vda2 /sysroot --mkdir
    mount /sysroot/images/arch.sqfs /sysroot/deploy
    mount -t overlay overlay -o lowerdir=/sysroot/deploy,upperdir=/sysroot/state/upper,workdir=/sysroot/state/work /new_root

    mount --rbind --mkdir /sysroot /new_root/sysroot
    # mount --rbind --mkdir /sysroot/state/containers /new_root/var/lib/containers

    launch_interactive_shell
}

run_hook() {
    mount_handler=mount_handler_overlay_rootfs
}
