#!/usr/bin/ash

mount_handler_overlay_rootfs() {
    echo "Mount handler for overlay rootfs"
    echo $*

    mount /dev/vda3 /mnt --mkdir
    mount /mnt/images/arch.sqfs /mnt/deploy
    mount -t overlay overlay -o lowerdir=/mnt/deploy,upperdir=/mnt/state/upper,workdir=/mnt/state/work /new_root

    mount --move /mnt /new_root/mnt

    launch_interactive_shell
}

run_hook() {
    mount_handler=mount_handler_overlay_rootfs
}
