name: Build and Release Arch Image

on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: "Cleanup disk space"
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
          df -h
      
      - name: Install Nix & Podman
        run: |
          bash <(curl -L https://nixos.org/nix/install) --daemon

          sudo -i -u root bash -c 'source /etc/profile.d/nix.sh && nix-env -iA nixpkgs.podman'

          sudo podman --version
      
      - name: Build Rust project
        run: |
          cd system && cargo build --release && cd -

      - name: Build artifact
        env:
          SYSTEM_USER: ${{ vars.SYSTEM_USER }}
          SYSTEM_PW: ${{ secrets.SYSTEM_PW }}
        run: |
          mkdir -p cache

          sudo -i
          . $HOME/.nix-profile/etc/profile.d/nix.sh
          sudo podman --version
          sudo podman build --cap-add ALL --build-context cache=./cache --build-arg SYSTEM_USER=$SYSTEM_USER --build-arg SYSTEM_PW=$SYSTEM_PW -t archbuild .
          podman create --name archbuild --replace archbuild
          podman cp archbuild:/arch.sqfs .
          podman cp archbuild:/mnt/usr/lib/kernel/arch-linux.efi .
          podman rm archbuild

          mkdir dist
          split --bytes=1G -d arch.sqfs dist/chunk-
          mv arch-linux.efi dist/

          sha256sum arch.sqfs dist/chunk-* dist/arch-linux.efi > dist/sha256sums.txt

          echo "Successfully built artifact"
      - name: Create Tag
        run: |
          git pull
          TAG=$(date +'%y.%m.%d-%H%M%S')
          echo TAG=$TAG >> $GITHUB_ENV
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          files: dist/*
